force-app/main/default/objects/Apex_Callout__c/Apex_Callout__c.object-meta.xml
<CustomObject>
    <description>Track all callouts from apex/ salesforce to third party services</description>
    <label>Apex Callout</label>
    <nameField>
        <displayFormat>CALL-{0000000}</displayFormat>
        <label>Apex Callout No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Callouts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Apex_Callout__c/fields/Callout_Type__c.field-meta.xml
<CustomField>
    <fullName>Callout_Type__c</fullName>
    <label>Callout Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>REST</fullName>
            </value>
            <value>
                <fullName>SOAP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apex_Callout__c/fields/Max_Attempts__c.field-meta.xml
<CustomField>
    <fullName>Max_Attempts__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Maximum retries for integration for this record.</description>
    <label>Max Attempts</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Apex_Callout__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <label>Module</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Auspost Workforce Management Module</fullName>
            </value>
            <value>
                <fullName>X Module</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/End_Point__mdt/End_Point__mdt.object-meta.xml
<CustomObject>
    <description>place for all defined end points used across SF instance</description>
    <label>End Point</label>
    <pluralLabel>End Points</pluralLabel>
</CustomObject>

force-app/main/default/objects/End_Point__mdt/fields/Callout_Type__c.field-meta.xml
<CustomField>
    <fullName>Callout_Type__c</fullName>
    <label>Callout Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SOAP</fullName>
                <default>true</default>
                <label>SOAP</label>
            </value>
            <value>
                <fullName>REST</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/End_Point__mdt/fields/Max_Attempts__c.field-meta.xml
<CustomField>
    <fullName>Max_Attempts__c</fullName>
    <description>Maximum re-tries to integrate</description>
    <label>Max Attempts</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/End_Point__mdt/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <description>End point URL</description>
    <label>URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
@isTest
public class TestDataFactory {
    public static List<Case> createCaseWithStatus(Integer noOfCases, String caseStatus) {
        List<Case> caseListToUpdate = new List<Case>();
        Account acc = new Account(Name = 'TestAccount'+System.Now());
        insert acc;
        Contact con = new Contact(LastName = 'TestContact'+System.Now(), AccountId = acc.Id);
        insert con;
        for(Integer i = 0 ; i < noOfCases; i++) {
            Case c = new Case();
            c.Subject = 'TestCase'+i;
            c.Status = caseStatus;
            caseListToUpdate.add(c);
        }
        insert caseListToUpdate;
        return caseListToUpdate;
    }

    public static List<Case> updateCaseStatus(List<Case> caseList, String caseStatus) {
        List<Case> caseListToUpdate = new List<Case>();
        for(Case c : caseList) {
            c.Status = caseStatus;
            caseListToUpdate.add(c);
        }
        update caseListToUpdate;
        return caseListToUpdate;
    }

    public static List<Apex_Callout__c> createIntegrationServiceRecord(List<Case> caseList) {
        List<End_Point__mdt> endpoint = [SELECT Module__c, CallOut_Type__c, URL__c, Max_Attempts__c FROM End_Point__mdt];
        List<Apex_Callout__c> integrationRecordList = apexCalloutTriggerHandler.createRecords(caseList, endpoint[0]);
        return integrationRecordList;
    }
}