force-app/main/default/objects/Apex_Callout__c/Apex_Callout__c.object-meta.xml
<CustomObject>
    <description>Track all callouts from apex/ salesforce to third party services</description>
    <label>Apex Callout</label>
    <nameField>
        <displayFormat>CALL-{0000000}</displayFormat>
        <label>Apex Callout No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Callouts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Apex_Callout__c/fields/Callout_Type__c.field-meta.xml
<CustomField>
    <fullName>Callout_Type__c</fullName>
    <label>Callout Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>REST</fullName>
            </value>
            <value>
                <fullName>SOAP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apex_Callout__c/fields/Max_Attempts__c.field-meta.xml
<CustomField>
    <fullName>Max_Attempts__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Maximum retries for integration for this record.</description>
    <label>Max Attempts</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Apex_Callout__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <label>Module</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Auspost Workforce Management Module</fullName>
            </value>
            <value>
                <fullName>X Module</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/End_Point__mdt/End_Point__mdt.object-meta.xml
<CustomObject>
    <description>place for all defined end points used across SF instance</description>
    <label>End Point</label>
    <pluralLabel>End Points</pluralLabel>
</CustomObject>

force-app/main/default/objects/End_Point__mdt/fields/Callout_Type__c.field-meta.xml
<CustomField>
    <fullName>Callout_Type__c</fullName>
    <label>Callout Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SOAP</fullName>
                <default>true</default>
                <label>SOAP</label>
            </value>
            <value>
                <fullName>REST</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/End_Point__mdt/fields/Max_Attempts__c.field-meta.xml
<CustomField>
    <fullName>Max_Attempts__c</fullName>
    <description>Maximum re-tries to integrate</description>
    <label>Max Attempts</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/End_Point__mdt/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <description>End point URL</description>
    <label>URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/caseTriggerHandler.cls
public with sharing class caseTriggerHandler {
    public static final String CLOSED_CASE = 'Closed';
    public static final String AUSPOST_HEROKU_SERVICE = 'Auspost_Heroku_Service';

    public static void handleCaseAfterUpdate(Map<Id, Case> oldMap, Map<Id, Case> newMap) {
        Map<Id, Case> selectedCaseMap = new Map<Id, Case>();
        for(Case c : newMap.Values()) {
            if(c.Status == CLOSED_CASE && oldMap.get(c.Id).Status <> CLOSED_CASE) {
                if(selectedCaseMap.get(c.Id) == null) {
                    selectedCaseMap.put(c.Id, new Case());
                }
                selectedCaseMap.put(c.Id, c);
            }
        }
        //callouts prep.
        if(selectedCaseMap.size() > 0) {
            List<Apex_Callout__c> calloutList = new List<Apex_Callout__c>();
            calloutList = createIntegrationRecords(selectedCaseMap);
        }
    }

    //creates/ updates records for integration object
    //keeps track of the integration status
    public static List<Apex_Callout__c> createIntegrationRecords(Map<Id, Case> caseMap) {
        End_Point__mdt endPoint = [SELECT URL__c, DeveloperName, Module__c, Max_Attempts__c, Callout_Type__c FROM End_Point__mdt WHERE DeveloperName = :AUSPOST_HEROKU_SERVICE];
        return apexCalloutTriggerHandler.createRecords(caseMap.Values(), endPoint);
    }
}