force-app/main/default/objects/Apex_Callout__c/Apex_Callout__c.object-meta.xml
<CustomObject>
    <description>Track all callouts from apex/ salesforce to third party services</description>
    <label>Apex Callout</label>
    <nameField>
        <displayFormat>CALL-{0000000}</displayFormat>
        <label>Apex Callout No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Callouts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Apex_Callout__c/fields/End_Point_URL__c.field-meta.xml
<CustomField>
    <fullName>End_Point_URL__c</fullName>
    <label>End Point URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Apex_Callout__c/fields/Record_Modified_By__c.field-meta.xml
<CustomField>
    <fullName>Record_Modified_By__c</fullName>
    <label>Record Modified By</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/caseIntegrationService.cls
// Specific CASE integration
public without sharing class caseIntegrationService implements iCallout {
    public static final String INTEGRATION_STATUS_PENDING = 'Pending';
    public static final String INTEGRATION_STATUS_COMPLETED = 'Completed';
    public static final String INTEGRATION_STATUS_FAILED = 'Failed';
    public static final Integer INTEGRATION_SERVICE_HTTP_SUCCESS = 200;

    public caseIntegrationService() {}

    public static HTTPRequest createHTTPRequest(String method, String timeOut, String endPoint, String header, String body) {
        Http h = new Http();        
        HttpRequest request = new HttpRequest();
        request.setEndpoint(endPoint);
        request.setMethod(method);
        request.setTimeout(integer.valueOf(timeOut));
        //set header
        request.setHeader('Content-Type', header);
        //set body
        request.setbody(body);
        return request;
    }

    public static Map<String, String> setHTTPCalloutParameters(Apex_Callout__c callout) {    
        //set header
        String header = 'multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW';
        //set payload
        String body = '------WebKitFormBoundary7MA4YWxkTrZu0gW\r\nContent-Disposition: form-data; name=\"id\"\r\n\r\n'+callout.Record_Id__c;
        body = body + '\r\n------WebKitFormBoundary7MA4YWxkTrZu0gW\r\nContent-Disposition: form-data; name=\"agentid\"\r\n\r\n'+callout.Record_Modified_By__c;
        body = body + '\r\n------WebKitFormBoundary7MA4YWxkTrZu0gW--';
        
        Map<String, String> parametersMap = new Map<String, String>();
        parametersMap.put('endPoint', callout.End_Point_URL__c);
        parametersMap.put('method', 'POST');
        parametersMap.put('timeOut', '120000');
        parametersMap.put('header', header);
        parametersMap.put('body', body);
        return parametersMap;
    }

    public static HTTPResponse sendHTTPRequest(Http h, HttpRequest request) {
        HttpResponse response = h.send(request);
        return response;
    }
}