force-app/main/default/objects/Apex_Callout__c/Apex_Callout__c.object-meta.xml
<CustomObject>
    <description>Track all callouts from apex/ salesforce to third party services</description>
    <label>Apex Callout</label>
    <nameField>
        <displayFormat>CALL-{0000000}</displayFormat>
        <label>Apex Callout No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Callouts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Apex_Callout__c/fields/Callout_Type__c.field-meta.xml
<CustomField>
    <fullName>Callout_Type__c</fullName>
    <label>Callout Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>REST</fullName>
            </value>
            <value>
                <fullName>SOAP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apex_Callout__c/fields/End_Point_URL__c.field-meta.xml
<CustomField>
    <fullName>End_Point_URL__c</fullName>
    <label>End Point URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Apex_Callout__c/fields/Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>Integration_Status__c</fullName>
    <defaultValue>&quot;Pending&quot;</defaultValue>
    <description>Pending = Newly created or failed callouts (less then or equal to n times)
Completed = Callout successfully completed
Failed = Callout failed (n times, no more retries)</description>
    <label>Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apex_Callout__c/fields/Max_Attempts__c.field-meta.xml
<CustomField>
    <fullName>Max_Attempts__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Maximum retries for integration for this record.</description>
    <label>Max Attempts</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Apex_Callout__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <label>Module</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Auspost Workforce Management Module</fullName>
            </value>
            <value>
                <fullName>X Module</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apex_Callout__c/fields/Record_Modified_By__c.field-meta.xml
<CustomField>
    <fullName>Record_Modified_By__c</fullName>
    <label>Record Modified By</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/End_Point__mdt/End_Point__mdt.object-meta.xml
<CustomObject>
    <description>place for all defined end points used across SF instance</description>
    <label>End Point</label>
    <pluralLabel>End Points</pluralLabel>
</CustomObject>

force-app/main/default/objects/End_Point__mdt/fields/Callout_Type__c.field-meta.xml
<CustomField>
    <fullName>Callout_Type__c</fullName>
    <label>Callout Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SOAP</fullName>
                <default>true</default>
                <label>SOAP</label>
            </value>
            <value>
                <fullName>REST</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/End_Point__mdt/fields/Max_Attempts__c.field-meta.xml
<CustomField>
    <fullName>Max_Attempts__c</fullName>
    <description>Maximum re-tries to integrate</description>
    <label>Max Attempts</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/End_Point__mdt/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <description>End point URL</description>
    <label>URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/apexCalloutTriggerHandler.cls
public with sharing class apexCalloutTriggerHandler {
    //creates record(s) for Integration based on 
    //1. list of cases
    //2. end point configuration provided
    public static List<Apex_Callout__c> createRecords(List<Case> caseList, End_Point__mdt endpoint) {
        if(caseList.isEmpty() || endpoint.URL__c == null || endpoint.URL__c == '') {
            return null;
        }

        List<Apex_Callout__c> calloutList = new List<Apex_Callout__c>();
        for(Case c : caseList) {
            Apex_Callout__c callout = new Apex_Callout__c(
                Integration_Status__c   = integrationService.INTEGRATION_STATUS_PENDING,
                Module__c               = endpoint.Module__c,
                Callout_Type__c         = endpoint.Callout_Type__c,
                Record_Id__c            = c.Id,
                End_Point_URL__c        = endpoint.URL__c,
                Record_Modified_By__c   = c.OwnerId,
                Max_Attempts__c         = endpoint.Max_Attempts__c
            );
            calloutList.add(callout);
        }
        try{
            Database.insert(calloutList, false);
        }catch(DMLException e) {
            System.debug(e);
            //log error
            return null;
        }
        return calloutList;
    }
}